"""System alert models for STORY-022-06: System Alerts and Monitoring

This module defines the SystemAlert and AlertRule models for managing
system alerts and alert configuration rules in the SIMRS system.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, ForeignKey, Enum as SQLEnum, Index, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.db.session import Base
from enum import Enum


class AlertSeverity(str, Enum):
    """Alert severity levels for system alerts"""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class AlertStatus(str, Enum):
    """Alert status options for system alerts"""
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class SystemAlert(Base):
    """System alert model for managing system alerts

    This model stores system alerts generated by various components
    including database, API, external services, and other system parts.
    """
    __tablename__ = "system_alerts"

    id = Column(Integer, primary_key=True, index=True)
    severity = Column(
        String(20),
        nullable=False,
        index=True,
        comment="Severity level of the alert"
    )
    component = Column(
        String(100),
        nullable=False,
        index=True,
        comment="System component that generated the alert (e.g., database, api, external_service)"
    )
    alert_type = Column(
        String(100),
        nullable=False,
        index=True,
        comment="Type of alert (e.g., database_down, api_timeout, sms_failure)"
    )
    message = Column(
        Text,
        nullable=False,
        comment="Alert message describing the issue"
    )
    details = Column(
        JSONB,
        nullable=True,
        comment="Additional details about the alert in JSON format"
    )
    status = Column(
        String(20),
        nullable=False,
        default="OPEN",
        index=True,
        comment="Current status of the alert"
    )
    acknowledged_by = Column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="User who acknowledged the alert"
    )
    acknowledged_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the alert was acknowledged"
    )
    resolved_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the alert was resolved"
    )
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Record creation timestamp"
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Record last update timestamp"
    )

    # Relationships
    acknowledged_by_user = relationship("User", foreign_keys=[acknowledged_by])

    # Indexes for common queries
    __table_args__ = (
        Index("ix_system_alerts_severity_status", "severity", "status"),
        Index("ix_system_alerts_component_status", "component", "status"),
        Index("ix_system_alerts_created_at", "created_at"),
    )


class AlertRule(Base):
    """Alert rule model for managing alert configuration rules

    This model stores alert configuration rules that define when and how
    alerts should be generated based on system conditions.
    """
    __tablename__ = "alert_rules"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique name for the alert rule"
    )
    component = Column(
        String(100),
        nullable=False,
        index=True,
        comment="System component this rule applies to"
    )
    alert_type = Column(
        String(100),
        nullable=False,
        comment="Type of alert to be generated by this rule"
    )
    severity = Column(
        String(20),
        nullable=False,
        comment="Severity level for alerts generated by this rule"
    )
    condition = Column(
        JSONB,
        nullable=False,
        comment="Rule conditions in JSON format defining when to trigger the alert"
    )
    enabled = Column(
        Boolean,
        default=True,
        nullable=False,
        index=True,
        comment="Whether the rule is currently enabled"
    )
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="Record creation timestamp"
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="Record last update timestamp"
    )

    # Indexes for common queries
    __table_args__ = (
        Index("ix_alert_rules_component_enabled", "component", "enabled"),
        Index("ix_alert_rules_name_enabled", "name", "enabled"),
    )
